"""
Item 4 (pedido del agente redactor): tabla suplementaria unica (Supplementary
Table S1), construida directamente desde los sinr_hibrido_oficial.json de los
9 escenarios (fuente autoritativa), uniendo lo que antes estaba repartido en
full_per_seat_table.csv y full_per_seat_table_con_incertidumbre.csv en un
solo archivo con una fila por (escenario, FOV, asiento):

  Pr_own_LOS_mW, Pr_interf_LOS_mW, Pr_DIFF_mW, Pr_interf_DIFF_mW,
  SINR_LOS_dB, SINR_DIFF_dB, SINR_hybrid_dB, canal elegido,
  n_rays_eq, exponente_d, +-dB_1sigma (del canal elegido)

No se corre ninguna simulacion nueva; todo sale de los JSON ya exportados
por pipeline_oficial.py. Ver generar_incertidumbre_todas_filas.py para la
derivacion de n/d/sigma (se reutiliza la misma formula aqui).
"""
import os, csv, json, math
import noise_model as nm

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.abspath(os.path.join(_THIS_DIR, ".."))
_TABLES_DIR = os.path.join(_PROJECT_ROOT, "resultados_generales", "tables")
os.makedirs(_TABLES_DIR, exist_ok=True)

RAY_ENERGY_W = 2.0e-6
ESCENARIOS = [
    "sin_bloqueo_0grados", "sin_bloqueo_15grados", "sin_bloqueo_30grados",
    "bloqueo_carrito_0grados", "bloqueo_carrito_15grados", "bloqueo_carrito_30grados",
    "bloqueo_persona_0grados", "bloqueo_persona_15grados", "bloqueo_persona_30grados",
]
RX_IDXS = [6, 7, 8, 9]
SEAT_OF_RX = {6: 1, 7: 2, 8: 3, 9: 4}  # mapeo asiento logico <-> indice NSC (ver agregar_diff_a_escenarios.py)


def n_rays_eq(pr_mw, fov_deg):
    g = nm.concentrator_gain(fov_deg)
    return (pr_mw / 1000.0 / g) / RAY_ENERGY_W


def real_exponent(pr_signal_mw, pr_interf_mw):
    pr_s, pr_i = pr_signal_mw / 1000.0, pr_interf_mw / 1000.0
    sinr, sigma2, i_sig, i_int = nm.compute_sinr(pr_s, pr_i)
    shot_signal_only = nm.shot_noise_variance(pr_s * nm.FILTER_TRANSMISSION)
    denom = sigma2 + i_int ** 2
    return float("nan") if denom <= 0 else 2.0 - shot_signal_only / denom


rows = []
for esc in ESCENARIOS:
    path = os.path.join(_PROJECT_ROOT, "escenarios", esc, "resultados", "sinr_hibrido_oficial.json")
    with open(path, encoding="utf-8") as f:
        filas = json.load(f)["filas"]
    for fila in filas:
        fov = fila["fov_deg"]
        for rx in RX_IDXS:
            a = fila["asientos"][str(rx)]
            usa_diff = a["usa_DIFF"]
            pr_signal = a["Pr_DIFF_mW"] if usa_diff else a["Pr_own_LOS_mW"]
            pr_interf = a["Pr_interf_DIFF_mW"] if usa_diff else a["Pr_interf_LOS_mW"]
            n = n_rays_eq(pr_signal, fov)
            if n <= 0:
                d, sigma_db = float("nan"), float("inf")
            else:
                d = real_exponent(pr_signal, pr_interf)
                sigma_db = d * (10.0 / math.log(10.0)) / math.sqrt(n)
            rows.append({
                "scenario": esc, "fov_deg": fov, "seat": SEAT_OF_RX[rx], "rx_obj": rx,
                "Pr_own_LOS_mW": a["Pr_own_LOS_mW"], "Pr_interf_LOS_mW": a["Pr_interf_LOS_mW"],
                "Pr_DIFF_mW": a["Pr_DIFF_mW"], "Pr_interf_DIFF_mW": a["Pr_interf_DIFF_mW"],
                "SINR_LOS_dB": a["SINR_LOS_dB"], "SINR_DIFF_dB": a["SINR_DIFF_dB"],
                "SINR_hybrid_dB": a["SINR_hybrid_dB"], "channel_used": "DIFF" if usa_diff else "LOS",
                "n_rays_eq": n, "exponent_d": d, "sigma_dB_1sigma": sigma_db,
            })

commit_hash = os.popen("git -C " + _PROJECT_ROOT + " rev-parse --short HEAD").read().strip()
csv_path = os.path.join(_TABLES_DIR, "supplementary_table_S1.csv")
readme_path = os.path.join(_TABLES_DIR, "supplementary_table_S1_README.txt")

with open(csv_path, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["scenario", "fov_deg", "seat", "rx_object_id", "Pr_own_LOS_mW", "Pr_interf_LOS_mW",
                "Pr_DIFF_mW", "Pr_interf_DIFF_mW", "SINR_LOS_dB", "SINR_DIFF_dB", "SINR_hybrid_dB",
                "channel_used", "n_rays_eq", "exponent_d", "sigma_dB_1sigma"])
    for r in rows:
        n_str = f"{r['n_rays_eq']:.1f}" if r["n_rays_eq"] == r["n_rays_eq"] else "0.0"
        d_str = f"{r['exponent_d']:.3f}" if r["exponent_d"] == r["exponent_d"] else "nan"
        s_str = f"{r['sigma_dB_1sigma']:.3f}" if r["sigma_dB_1sigma"] != float("inf") else "inf"
        w.writerow([r["scenario"], r["fov_deg"], r["seat"], r["rx_obj"], f"{r['Pr_own_LOS_mW']:.4f}",
                    f"{r['Pr_interf_LOS_mW']:.4f}", f"{r['Pr_DIFF_mW']:.4f}", f"{r['Pr_interf_DIFF_mW']:.4f}",
                    f"{r['SINR_LOS_dB']:.2f}", f"{r['SINR_DIFF_dB']:.2f}", f"{r['SINR_hybrid_dB']:.2f}",
                    r["channel_used"], n_str, d_str, s_str])

readme = f"""Supplementary Table S1 -- single consolidated dataset (9 scenarios x 9 FOV x 4 seats = 324 rows)
Generated by codigo_comun/generar_tabla_suplementaria_s1.py
Commit: {commit_hash}
Stable path (repo-relative): resultados_generales/tables/supplementary_table_S1.csv

Columns and units:
  scenario        : blockage scenario + pitch, e.g. "bloqueo_persona_30grados"
  fov_deg         : receiver field-of-view cutoff applied in post-processing (degrees)
  seat            : logical seat number 1-4 (seat = rx_object_id - 5, see agregar_diff_a_escenarios.py)
  rx_object_id    : Zemax NSC detector object index (6,7,8,9)
  Pr_own_LOS_mW   : received optical power from the seat's own LOS lamp, mW.
                    Concentrator gain g(FOV) IS already applied (Kahn&Barry, eta*n^2/sin^2(FOV)).
                    Optical filter transmission T_f (0.90) is NOT applied -- T_f is applied only
                    inside noise_model.compute_sinr() when converting to photocurrent, not baked
                    into the exported Pr. Multiply by noise_model.FILTER_TRANSMISSION if you need
                    post-filter power (see generar_tabla_validacion_analitica_ingles.py).
  Pr_interf_LOS_mW: received optical power from the OTHER 3 LOS lamps (co-channel interference), mW.
                    Same gain/filter convention as Pr_own_LOS_mW.
  Pr_DIFF_mW      : received optical power from the DIFF (backup/diffuse) source, mW. Same convention.
  Pr_interf_DIFF_mW: interference power on the DIFF channel, mW. Always 0.0 in this dataset (the
                    model has a single DIFF source, no co-channel interference on that band).
  SINR_LOS_dB, SINR_DIFF_dB, SINR_hybrid_dB: per noise_model.compute_sinr(); hybrid = max(LOS,DIFF).
  channel_used    : which of LOS/DIFF achieves SINR_hybrid for that row.
  n_rays_eq       : equivalent number of Monte Carlo rays behind Pr of channel_used, recovered as
                    (Pr_mW/1000/g(FOV)) / (Popt/N_RAYS), Popt=2W, N_RAYS=1e6 (2 microW/ray).
  exponent_d      : real local exponent of SINR(n) ~ n^d for channel_used, d = 2 - shot_signal /
                    (total_noise_variance + I_interference^2); see generar_incertidumbre_todas_filas.py.
  sigma_dB_1sigma : +-dB (1 sigma) Poisson ray-count uncertainty on SINR_hybrid_dB for that row,
                    = exponent_d * (10/ln10) / sqrt(n_rays_eq).

No new Zemax simulation was run to build this file; all values are read from the already-exported
escenarios/*/resultados/sinr_hibrido_oficial.json files.
"""
with open(readme_path, "w", encoding="utf-8") as f:
    f.write(readme)

print(f"{len(rows)} filas en {csv_path}")
print(f"README: {readme_path}")
print(f"Commit: {commit_hash}")
